import { Preset } from '../types';

export const PRESETS: Preset[] = [
  // 主食 ─ ごはん系
  { name: 'サトウのごはん 200g', sec: 'staple', kcal: 294, waterL: 0 },
  { name: 'サトウのごはん 銀シャリ', sec: 'staple', kcal: 294, waterL: 0 },
  { name: 'サトウのごはん 麦ごはん', sec: 'staple', kcal: 276, waterL: 0 },
  { name: 'パックごはん（レトルト）', sec: 'staple', kcal: 294, waterL: 0 },
  { name: '尾西のアルファ米 白飯', sec: 'staple', kcal: 370, waterL: 0 },
  { name: '尾西のアルファ米 五目ごはん', sec: 'staple', kcal: 380, waterL: 0 },
  { name: '尾西のアルファ米 わかめごはん', sec: 'staple', kcal: 360, waterL: 0 },
  { name: '尾西のアルファ米 ドライカレー', sec: 'staple', kcal: 390, waterL: 0 },
  { name: '尾西のアルファ米 松茸ごはん', sec: 'staple', kcal: 370, waterL: 0 },
  { name: '尾西のアルファ米 赤飯', sec: 'staple', kcal: 355, waterL: 0 },
  { name: '尾西のアルファ米 山菜おこわ', sec: 'staple', kcal: 365, waterL: 0 },
  { name: '尾西のアルファ米 梅がゆ', sec: 'staple', kcal: 150, waterL: 0 },
  { name: 'アルファ米 白飯', sec: 'staple', kcal: 370, waterL: 0 },
  { name: 'アルファ米 五目ごはん', sec: 'staple', kcal: 380, waterL: 0 },
  // 主食 ─ パン・麺・その他
  { name: '乾パン', sec: 'staple', kcal: 410, waterL: 0 },
  { name: 'パンの缶詰（メープル）', sec: 'staple', kcal: 350, waterL: 0 },
  { name: 'パンの缶詰（チョコ）', sec: 'staple', kcal: 360, waterL: 0 },
  { name: 'パンの缶詰（プレーン）', sec: 'staple', kcal: 340, waterL: 0 },
  { name: 'ボローニャ 缶deボローニャ', sec: 'staple', kcal: 360, waterL: 0 },
  { name: 'カロリーメイト ブロック', sec: 'staple', kcal: 400, waterL: 0 },
  { name: 'クラッカー', sec: 'staple', kcal: 450, waterL: 0 },
  { name: 'リッツ', sec: 'staple', kcal: 490, waterL: 0 },
  { name: '餅（切り餅）', sec: 'staple', kcal: 230, waterL: 0 },
  { name: 'インスタントラーメン', sec: 'staple', kcal: 450, waterL: 0 },
  { name: 'カップヌードル', sec: 'staple', kcal: 350, waterL: 0 },
  { name: 'どん兵衛', sec: 'staple', kcal: 410, waterL: 0 },
  { name: 'マルタイ 棒ラーメン', sec: 'staple', kcal: 350, waterL: 0 },
  { name: 'パスタ（乾麺）', sec: 'staple', kcal: 370, waterL: 0 },
  { name: 'そうめん（乾麺）', sec: 'staple', kcal: 340, waterL: 0 },
  { name: 'シリアル（コーンフレーク）', sec: 'staple', kcal: 380, waterL: 0 },
  { name: 'グラノーラ', sec: 'staple', kcal: 440, waterL: 0 },
  // 主菜・缶詰・レトルト
  { name: 'ツナ缶（はごろもシーチキン）', sec: 'side', kcal: 210, waterL: 0 },
  { name: 'ツナ缶（ノンオイル）', sec: 'side', kcal: 120, waterL: 0 },
  { name: 'サバ味噌煮缶', sec: 'side', kcal: 280, waterL: 0 },
  { name: 'サバ水煮缶', sec: 'side', kcal: 190, waterL: 0 },
  { name: 'イワシ缶（味付）', sec: 'side', kcal: 220, waterL: 0 },
  { name: 'サンマ蒲焼缶', sec: 'side', kcal: 250, waterL: 0 },
  { name: '焼き鳥缶（タレ）', sec: 'side', kcal: 180, waterL: 0 },
  { name: '焼き鳥缶（塩）', sec: 'side', kcal: 160, waterL: 0 },
  { name: 'コンビーフ', sec: 'side', kcal: 200, waterL: 0 },
  { name: 'スパム', sec: 'side', kcal: 300, waterL: 0 },
  { name: 'ウインナー缶', sec: 'side', kcal: 260, waterL: 0 },
  { name: 'ボンカレーゴールド', sec: 'side', kcal: 220, waterL: 0 },
  { name: 'カレーレトルト', sec: 'side', kcal: 220, waterL: 0 },
  { name: 'ククレカレー', sec: 'side', kcal: 200, waterL: 0 },
  { name: '牛丼の具（レトルト）', sec: 'side', kcal: 250, waterL: 0 },
  { name: '親子丼の具（レトルト）', sec: 'side', kcal: 200, waterL: 0 },
  { name: '中華丼の具（レトルト）', sec: 'side', kcal: 180, waterL: 0 },
  { name: 'ハヤシライス（レトルト）', sec: 'side', kcal: 210, waterL: 0 },
  { name: 'パスタソース（ミートソース）', sec: 'side', kcal: 180, waterL: 0 },
  { name: 'パスタソース（たらこ）', sec: 'side', kcal: 120, waterL: 0 },
  { name: 'おかゆ（レトルト）', sec: 'side', kcal: 80, waterL: 0 },
  { name: 'フルーツ缶（みかん）', sec: 'side', kcal: 80, waterL: 0 },
  { name: 'フルーツ缶（桃）', sec: 'side', kcal: 90, waterL: 0 },
  { name: 'フルーツ缶（パイン）', sec: 'side', kcal: 85, waterL: 0 },
  { name: 'コーン缶', sec: 'side', kcal: 100, waterL: 0 },
  { name: 'トマト缶', sec: 'side', kcal: 40, waterL: 0 },
  { name: '大豆水煮缶', sec: 'side', kcal: 130, waterL: 0 },
  // 飲料・水
  { name: '保存水 2L', sec: 'drink', kcal: 0, waterL: 2 },
  { name: '保存水 500ml', sec: 'drink', kcal: 0, waterL: 0.5 },
  { name: '10年保存水 2L', sec: 'drink', kcal: 0, waterL: 2 },
  { name: 'い・ろ・は・す 555ml', sec: 'drink', kcal: 0, waterL: 0.555 },
  { name: 'クリスタルガイザー 500ml', sec: 'drink', kcal: 0, waterL: 0.5 },
  { name: 'サントリー天然水 2L', sec: 'drink', kcal: 0, waterL: 2 },
  { name: '野菜ジュース 200ml', sec: 'drink', kcal: 70, waterL: 0.2 },
  { name: 'カゴメ 野菜一日これ一本', sec: 'drink', kcal: 70, waterL: 0.2 },
  { name: 'トマトジュース 200ml', sec: 'drink', kcal: 40, waterL: 0.2 },
  { name: 'スポーツドリンク 500ml', sec: 'drink', kcal: 25, waterL: 0.5 },
  { name: 'ポカリスエット 500ml', sec: 'drink', kcal: 125, waterL: 0.5 },
  { name: 'アクエリアス 500ml', sec: 'drink', kcal: 95, waterL: 0.5 },
  { name: '経口補水液 OS-1 500ml', sec: 'drink', kcal: 10, waterL: 0.5 },
  { name: 'お茶ペットボトル 500ml', sec: 'drink', kcal: 0, waterL: 0.5 },
  { name: 'おーいお茶 525ml', sec: 'drink', kcal: 0, waterL: 0.525 },
  { name: '缶コーヒー', sec: 'drink', kcal: 65, waterL: 0.19 },
  { name: '粉末ポカリスエット', sec: 'drink', kcal: 27, waterL: 0 },
  { name: '青汁（粉末）', sec: 'drink', kcal: 10, waterL: 0 },
  // 副菜・補助食 ─ ようかん・ビスケット系
  { name: '井村屋 えいようかん', sec: 'snack', kcal: 170, waterL: 0 },
  { name: '井村屋 えいようかん チョコ味', sec: 'snack', kcal: 170, waterL: 0 },
  { name: 'えいようかん', sec: 'snack', kcal: 170, waterL: 0 },
  { name: 'ようかん', sec: 'snack', kcal: 290, waterL: 0 },
  { name: 'グリコ ビスコ保存缶', sec: 'snack', kcal: 400, waterL: 0 },
  { name: 'ビスコ保存缶', sec: 'snack', kcal: 400, waterL: 0 },
  { name: 'ミレービスケット', sec: 'snack', kcal: 500, waterL: 0 },
  { name: 'ブルボン カンパン', sec: 'snack', kcal: 410, waterL: 0 },
  { name: 'ブルボン 缶入ミニクラッカー', sec: 'snack', kcal: 470, waterL: 0 },
  // 副菜・補助食 ─ チョコ・飴・ナッツ
  { name: 'チョコレート', sec: 'snack', kcal: 550, waterL: 0 },
  { name: '明治 ミルクチョコレート', sec: 'snack', kcal: 560, waterL: 0 },
  { name: '森永 チョコボール', sec: 'snack', kcal: 510, waterL: 0 },
  { name: '氷砂糖', sec: 'snack', kcal: 390, waterL: 0 },
  { name: '飴（キャンディ）', sec: 'snack', kcal: 390, waterL: 0 },
  { name: '龍角散 のどすっきり飴', sec: 'snack', kcal: 380, waterL: 0 },
  { name: 'カンロ ノンシュガー果実のど飴', sec: 'snack', kcal: 280, waterL: 0 },
  { name: 'ドライフルーツ', sec: 'snack', kcal: 350, waterL: 0 },
  { name: 'ドライマンゴー', sec: 'snack', kcal: 330, waterL: 0 },
  { name: 'ナッツミックス', sec: 'snack', kcal: 600, waterL: 0 },
  { name: '小魚アーモンド', sec: 'snack', kcal: 480, waterL: 0 },
  // 副菜・補助食 ─ プロテイン・栄養補助
  { name: 'プロテインバー', sec: 'snack', kcal: 200, waterL: 0 },
  { name: 'inバープロテイン', sec: 'snack', kcal: 210, waterL: 0 },
  { name: 'カロリーメイト ゼリー', sec: 'snack', kcal: 200, waterL: 0.2 },
  { name: 'ウイダーinゼリー エネルギー', sec: 'snack', kcal: 180, waterL: 0.18 },
  { name: 'ウイダーinゼリー マルチビタミン', sec: 'snack', kcal: 90, waterL: 0.18 },
  { name: '大塚製薬 カロリーメイト缶', sec: 'snack', kcal: 200, waterL: 0.2 },
  { name: 'マルチビタミン（サプリ）', sec: 'snack', kcal: 5, waterL: 0 },
  // 調味料・その他
  { name: 'ふりかけ各種', sec: 'seasoning', kcal: 20, waterL: 0 },
  { name: '粉末スープ', sec: 'seasoning', kcal: 45, waterL: 0 },
  { name: '味噌（フリーズドライ）', sec: 'seasoning', kcal: 30, waterL: 0 },
  { name: '醤油（小袋）', sec: 'seasoning', kcal: 5, waterL: 0 },
  { name: '塩', sec: 'seasoning', kcal: 0, waterL: 0 },
  { name: '砂糖（スティック）', sec: 'seasoning', kcal: 15, waterL: 0 },
  { name: 'マヨネーズ', sec: 'seasoning', kcal: 100, waterL: 0 },
  { name: 'ケチャップ', sec: 'seasoning', kcal: 20, waterL: 0 },
  // 防災グッズ ─ トイレ・衛生
  { name: '簡易トイレセット', sec: 'bousai', kcal: 0, waterL: 0 },
  { name: 'BOS 非常用トイレセット 50回分', sec: 'bousai', kcal: 0, waterL: 0 },
  { name: '驚異の防臭袋BOS 15枚', sec: 'bousai', kcal: 0, waterL: 0 },
  { name: 'マイレット 簡易トイレ 10回分', sec: 'bousai', kcal: 0, waterL: 0 },
  { name: 'ウェットティッシュ', sec: 'bousai', kcal: 0, waterL: 0 },
  { name: 'シルコット ウェットティッシュ', sec: 'bousai', kcal: 0, waterL: 0 },
  { name: '除菌アルコールシート', sec: 'bousai', kcal: 0, waterL: 0 },
  { name: 'マスク', sec: 'bousai', kcal: 0, waterL: 0 },
  { name: 'N95マスク', sec: 'bousai', kcal: 0, waterL: 0 },
  { name: '歯磨きシート', sec: 'bousai', kcal: 0, waterL: 0 },
  { name: 'ドライシャンプー', sec: 'bousai', kcal: 0, waterL: 0 },
  { name: 'からだふき（大判）', sec: 'bousai', kcal: 0, waterL: 0 },
  { name: '生理用品', sec: 'bousai', kcal: 0, waterL: 0 },
  { name: 'おむつ（乳幼児用）', sec: 'bousai', kcal: 0, waterL: 0 },
  { name: 'おしりふき', sec: 'bousai', kcal: 0, waterL: 0 },
  // 防災グッズ ─ ライフライン
  { name: 'カセットコンロ用ボンベ', sec: 'bousai', kcal: 0, waterL: 0 },
  { name: 'イワタニ カセットガス 3本', sec: 'bousai', kcal: 0, waterL: 0 },
  { name: 'カセットコンロ', sec: 'bousai', kcal: 0, waterL: 0 },
  { name: 'イワタニ カセットフー', sec: 'bousai', kcal: 0, waterL: 0 },
  { name: '乾電池（単3）', sec: 'bousai', kcal: 0, waterL: 0 },
  { name: 'Panasonic エボルタNEO 単3', sec: 'bousai', kcal: 0, waterL: 0 },
  { name: '乾電池（単1）', sec: 'bousai', kcal: 0, waterL: 0 },
  { name: 'Panasonic エボルタNEO 単1', sec: 'bousai', kcal: 0, waterL: 0 },
  { name: '携帯充電器（モバイルバッテリー）', sec: 'bousai', kcal: 0, waterL: 0 },
  { name: 'Anker PowerCore 10000', sec: 'bousai', kcal: 0, waterL: 0 },
  { name: 'Anker PowerCore 20000', sec: 'bousai', kcal: 0, waterL: 0 },
  { name: 'ソーラー充電器', sec: 'bousai', kcal: 0, waterL: 0 },
  { name: '手回し充電ラジオライト', sec: 'bousai', kcal: 0, waterL: 0 },
  // 防災グッズ ─ 照明・工具
  { name: 'LEDランタン', sec: 'bousai', kcal: 0, waterL: 0 },
  { name: 'GENTOS LEDランタン', sec: 'bousai', kcal: 0, waterL: 0 },
  { name: 'LEDヘッドライト', sec: 'bousai', kcal: 0, waterL: 0 },
  { name: '懐中電灯', sec: 'bousai', kcal: 0, waterL: 0 },
  { name: 'ろうそく（非常用）', sec: 'bousai', kcal: 0, waterL: 0 },
  { name: '軍手', sec: 'bousai', kcal: 0, waterL: 0 },
  { name: '耐切創手袋', sec: 'bousai', kcal: 0, waterL: 0 },
  { name: '万能ナイフ', sec: 'bousai', kcal: 0, waterL: 0 },
  { name: 'ガムテープ', sec: 'bousai', kcal: 0, waterL: 0 },
  // 防災グッズ ─ 保温・防護
  { name: 'ラップ', sec: 'bousai', kcal: 0, waterL: 0 },
  { name: 'ブルーシート', sec: 'bousai', kcal: 0, waterL: 0 },
  { name: 'アルミブランケット', sec: 'bousai', kcal: 0, waterL: 0 },
  { name: 'SOL エマージェンシーブランケット', sec: 'bousai', kcal: 0, waterL: 0 },
  { name: '寝袋（コンパクト）', sec: 'bousai', kcal: 0, waterL: 0 },
  { name: 'カイロ', sec: 'bousai', kcal: 0, waterL: 0 },
  { name: '桐灰 マグマ貼るカイロ', sec: 'bousai', kcal: 0, waterL: 0 },
  { name: 'レインコート（使い捨て）', sec: 'bousai', kcal: 0, waterL: 0 },
  // 防災グッズ ─ 救急・その他
  { name: '救急セット', sec: 'bousai', kcal: 0, waterL: 0 },
  { name: '絆創膏', sec: 'bousai', kcal: 0, waterL: 0 },
  { name: '包帯・三角巾', sec: 'bousai', kcal: 0, waterL: 0 },
  { name: '常備薬', sec: 'bousai', kcal: 0, waterL: 0 },
  { name: 'ホイッスル（防災笛）', sec: 'bousai', kcal: 0, waterL: 0 },
  { name: '防災ラジオ', sec: 'bousai', kcal: 0, waterL: 0 },
  { name: 'ゴミ袋（45L 黒）', sec: 'bousai', kcal: 0, waterL: 0 },
  { name: 'ポリタンク 10L', sec: 'bousai', kcal: 0, waterL: 0 },
  { name: '給水袋 5L', sec: 'bousai', kcal: 0, waterL: 0 },
  { name: '紙皿・紙コップセット', sec: 'bousai', kcal: 0, waterL: 0 },
  { name: '割り箸・スプーンセット', sec: 'bousai', kcal: 0, waterL: 0 },
];
