import { RegionProfile } from '../types';

export const REGION_PROFILES: RegionProfile[] = [
  {
    id: 'nankai',
    name: '南海トラフ想定地域',
    icon: '🌊',
    days: 14,
    color: '#5C9CE6',
    risks: ['地震', '津波'],
    extra: '軽量持ち出しセットがあると便利です',
    areas: '四国全域・紀伊半島・東海沿岸・九州東岸',
    source: '内閣府 南海トラフ地震対策',
  },
  {
    id: 'shutoken',
    name: '首都直下地震想定',
    icon: '🏙️',
    days: 10,
    color: '#7BAEDC',
    risks: ['地震', '帰宅困難', '停電'],
    extra: '簡易トイレや携帯備蓄があると安心です',
    areas: '東京23区・神奈川東部・千葉西部・埼玉南部',
    source: '内閣府 首都直下地震対策',
  },
  {
    id: 'snow',
    name: '豪雪地帯',
    icon: '❄️',
    days: 10,
    color: '#7EC8D9',
    risks: ['大雪', '停電', '交通障害'],
    extra: '防寒グッズ（カイロ・毛布）を追加すると安心です',
    areas: '北海道・東北日本海側・北陸・山間部',
    source: '国土交通省 豪雪地帯指定',
  },
  {
    id: 'remote',
    name: '山間部・離島',
    icon: '🏔️',
    days: 14,
    color: '#8DC5A0',
    risks: ['交通障害', '物流遅延'],
    extra: '余裕をもった長期の備蓄がおすすめです',
    areas: '全国の中山間地域・離島',
    source: '内閣府 防災白書',
  },
  {
    id: 'general',
    name: '一般都市部',
    icon: '🏘️',
    days: 7,
    color: '#82C9A0',
    risks: ['地震', '台風'],
    extra: '標準的な備蓄で十分です',
    areas: '上記以外の地域',
    source: '内閣府 防災ガイドライン',
  },
];
